/* ============================================================
   THE ROM-COM ARCHIVE — Movie Data
   A curated dataset of romantic comedies (1990–2026).
   Poster art uses themed gradient placeholders (no external
   image hosting dependency) — swap `poster` values for real
   image paths/URLs whenever you have licensed artwork.
   ============================================================ */

const MOVIES = [
  {
    id: "pretty-woman",
    title: "Pretty Woman",
    year: 1990,
    decade: "1990s",
    runtime: 119,
    director: "Garry Marshall",
    writer: "J.F. Lawton",
    cast: ["Julia Roberts", "Richard Gere", "Jason Alexander"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Workplace Romance"],
    country: "USA",
    rating: 7.0,
    awardWinner: true,
    synopsis: "A businessman falls for a charming escort he hires as an arm-piece for social events, and their arrangement blossoms into something neither expected.",
    awards: "Golden Globe — Best Actress (Musical/Comedy), 1991",
    trivia: "Julia Roberts was paid $300,000 for the role — a fraction of what she'd command after the film's success.",
    poster: "linear-gradient(160deg,#7a1f2b,#d1495b)"
  },
  {
    id: "sleepless-in-seattle",
    title: "Sleepless in Seattle",
    year: 1993,
    decade: "1990s",
    runtime: 105,
    director: "Nora Ephron",
    writer: "Nora Ephron, David S. Ward",
    cast: ["Tom Hanks", "Meg Ryan", "Ross Malinger"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance", "Road Trip"],
    country: "USA",
    rating: 6.8,
    awardWinner: false,
    synopsis: "A widower's son calls a radio talk show hoping to find his father a new wife, catching the attention of a woman across the country who feels an inexplicable pull toward him.",
    awards: "Nominated — Academy Award for Best Original Screenplay",
    trivia: "Tom Hanks and Meg Ryan share almost no screen time together until the final scene atop the Empire State Building.",
    poster: "linear-gradient(160deg,#1c2b4a,#3d6ea5)"
  },
  {
    id: "four-weddings",
    title: "Four Weddings and a Funeral",
    year: 1994,
    decade: "1990s",
    runtime: 117,
    director: "Mike Newell",
    writer: "Richard Curtis",
    cast: ["Hugh Grant", "Andie MacDowell", "Kristin Scott Thomas"],
    genres: ["Romance", "Comedy"],
    tropes: ["Wedding", "Second Chance"],
    country: "UK",
    rating: 7.1,
    awardWinner: true,
    synopsis: "A commitment-phobic Englishman keeps crossing paths with an alluring American at a string of weddings — and one funeral — over several years.",
    awards: "BAFTA — Best Film, 1995",
    trivia: "The film was made for just £2.7 million and became one of the highest-grossing British films of all time.",
    poster: "linear-gradient(160deg,#2a2a2a,#e5c14a)"
  },
  {
    id: "clueless",
    title: "Clueless",
    year: 1995,
    decade: "1990s",
    runtime: 97,
    director: "Amy Heckerling",
    writer: "Amy Heckerling",
    cast: ["Alicia Silverstone", "Paul Rudd", "Stacey Dash"],
    genres: ["Comedy", "Romance"],
    tropes: ["Friends to Lovers"],
    country: "USA",
    rating: 6.9,
    awardWinner: false,
    synopsis: "A wealthy, well-meaning Beverly Hills teenager plays matchmaker for her classmates while dodging the realization that romance has been in front of her all along.",
    awards: "Nominated — MTV Movie Award for Best Movie, 1996",
    trivia: "Loosely inspired by Jane Austen's Emma, updated to 1990s Los Angeles high-school life.",
    poster: "linear-gradient(160deg,#5b2a6e,#d1495b)"
  },
  {
    id: "youve-got-mail",
    title: "You've Got Mail",
    year: 1998,
    decade: "1990s",
    runtime: 119,
    director: "Nora Ephron",
    writer: "Nora Ephron, Delia Ephron",
    cast: ["Tom Hanks", "Meg Ryan", "Greg Kinnear"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers"],
    country: "USA",
    rating: 6.8,
    awardWinner: false,
    synopsis: "Two business rivals who despise each other in person are, unknowingly, falling in love through anonymous emails.",
    awards: "Nominated — Golden Globe for Best Actress, 1999",
    trivia: "A loose remake of the 1940 film The Shop Around the Corner, updated for the dawn of the internet age.",
    poster: "linear-gradient(160deg,#264d3b,#e5c14a)"
  },
  {
    id: "notting-hill",
    title: "Notting Hill",
    year: 1999,
    decade: "1990s",
    runtime: 124,
    director: "Roger Michell",
    writer: "Richard Curtis",
    cast: ["Julia Roberts", "Hugh Grant", "Rhys Ifans"],
    genres: ["Romance", "Comedy"],
    tropes: ["Fake Dating", "Second Chance"],
    country: "UK",
    rating: 7.2,
    awardWinner: false,
    synopsis: "An ordinary London bookshop owner's life turns upside down when the world's most famous actress walks through his door.",
    awards: "Nominated — BAFTA for Best British Film, 2000",
    trivia: "The bookshop in the film inspired a real travel bookshop of the same name that still operates in Notting Hill.",
    poster: "linear-gradient(160deg,#1e2a3a,#5b7fa6)"
  },
  {
    id: "10-things",
    title: "10 Things I Hate About You",
    year: 1999,
    decade: "1990s",
    runtime: 97,
    director: "Gil Junger",
    writer: "Karen McCullah, Kirsten Smith",
    cast: ["Heath Ledger", "Julia Stiles", "Joseph Gordon-Levitt"],
    genres: ["Comedy", "Romance", "Teen"],
    tropes: ["Enemies to Lovers"],
    country: "USA",
    rating: 7.3,
    awardWinner: false,
    synopsis: "A high schooler is paid to secretly woo a fiercely independent, difficult girl so her younger sister can finally date.",
    awards: "MTV Movie Award — Best Comedic Performance, 2000",
    trivia: "A modern teen retelling of Shakespeare's The Taming of the Shrew.",
    poster: "linear-gradient(160deg,#3a1e2a,#d1495b)"
  },
  {
    id: "legally-blonde",
    title: "Legally Blonde",
    year: 2001,
    decade: "2000s",
    runtime: 96,
    director: "Robert Luketic",
    writer: "Karen McCullah, Kirsten Smith",
    cast: ["Reese Witherspoon", "Luke Wilson", "Selma Blair"],
    genres: ["Comedy", "Romance"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A sorority queen follows her ex to Harvard Law School to win him back — and discovers she has exactly what it takes to win on her own terms.",
    awards: "Nominated — Golden Globe for Best Actress, 2002",
    trivia: "Reese Witherspoon reportedly based Elle Woods' optimism on people she knew growing up in Nashville.",
    poster: "linear-gradient(160deg,#5b2a6e,#e5c14a)"
  },
  {
    id: "how-to-lose-a-guy",
    title: "How to Lose a Guy in 10 Days",
    year: 2003,
    decade: "2000s",
    runtime: 116,
    director: "Donald Petrie",
    writer: "Kristen Buckley, Brian Regan",
    cast: ["Kate Hudson", "Matthew McConaughey", "Adam Goldberg"],
    genres: ["Romance", "Comedy"],
    tropes: ["Fake Dating", "Enemies to Lovers"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A magazine columnist trying to prove a dating theory and an ad executive trying to win a bet both use each other — and fall for real.",
    awards: "Nominated — Teen Choice Award, 2003",
    trivia: "The diamond necklace featured in the film was a real, working piece worth over $5 million.",
    poster: "linear-gradient(160deg,#2a3a1e,#e5c14a)"
  },
  {
    id: "love-actually",
    title: "Love Actually",
    year: 2003,
    decade: "2000s",
    runtime: 135,
    director: "Richard Curtis",
    writer: "Richard Curtis",
    cast: ["Hugh Grant", "Emma Thompson", "Colin Firth", "Keira Knightley"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Holiday Romance", "Workplace Romance"],
    country: "UK",
    rating: 7.6,
    awardWinner: true,
    synopsis: "Ten intertwined London love stories unfold in the five weeks before Christmas, ranging from the joyful to the bittersweet.",
    awards: "BAFTA — Britannia Award, 2003",
    trivia: "Richard Curtis wrote the script as a deliberate love letter to the ensemble rom-coms of the 1990s.",
    poster: "linear-gradient(160deg,#3a1e1e,#e5c14a)"
  },
  {
    id: "13-going-on-30",
    title: "13 Going on 30",
    year: 2004,
    decade: "2000s",
    runtime: 98,
    director: "Gary Winick",
    writer: "Josh Goldsmith, Cathy Yuspa",
    cast: ["Jennifer Garner", "Mark Ruffalo", "Judy Greer"],
    genres: ["Comedy", "Romance", "Fantasy"],
    tropes: ["Friends to Lovers", "Second Chance"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A thirteen-year-old wishes to be thirty, flirty, and thriving — and wakes up seventeen years later having missed the life she actually built.",
    awards: "Nominated — Teen Choice Award, 2004",
    trivia: "The dance sequence to 'Thriller' was almost cut before test audiences responded so strongly it stayed in.",
    poster: "linear-gradient(160deg,#5b3a1e,#e5c14a)"
  },
  {
    id: "the-notebook",
    title: "The Notebook",
    year: 2004,
    decade: "2000s",
    runtime: 123,
    director: "Nick Cassavetes",
    writer: "Jeremy Leven, Jan Sardi",
    cast: ["Ryan Gosling", "Rachel McAdams", "James Garner"],
    genres: ["Romance", "Drama"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 7.8,
    awardWinner: true,
    synopsis: "A poor young man and a wealthy young woman fall deeply in love one summer, only to be separated by class and circumstance — with a lifetime still ahead of them.",
    awards: "MTV Movie Award — Best Kiss, 2005",
    trivia: "Ryan Gosling and Rachel McAdams reportedly did not get along during filming, despite their famous on-screen chemistry.",
    poster: "linear-gradient(160deg,#1e2a3a,#d1495b)"
  },
  {
    id: "hitch",
    title: "Hitch",
    year: 2005,
    decade: "2000s",
    runtime: 118,
    director: "Andy Tennant",
    writer: "Kevin Bisch",
    cast: ["Will Smith", "Eva Mendes", "Kevin James"],
    genres: ["Romance", "Comedy"],
    tropes: ["Workplace Romance"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "A professional 'date doctor' who coaches hapless men through romance meets his match in a sharp-eyed gossip columnist.",
    awards: "Nominated — People's Choice Award, 2006",
    trivia: "Will Smith trained extensively to make the film's physical comedy sequences look effortless.",
    poster: "linear-gradient(160deg,#2a2a2a,#3d6ea5)"
  },
  {
    id: "the-holiday",
    title: "The Holiday",
    year: 2006,
    decade: "2000s",
    runtime: 138,
    director: "Nancy Meyers",
    writer: "Nancy Meyers",
    cast: ["Cameron Diaz", "Kate Winslet", "Jude Law", "Jack Black"],
    genres: ["Romance", "Comedy"],
    tropes: ["Holiday Romance", "Second Chance"],
    country: "USA",
    rating: 6.9,
    awardWinner: false,
    synopsis: "Two heartbroken women on opposite sides of the world swap homes for the holidays and find unexpected romance in each other's lives.",
    awards: "Nominated — Golden Globe for Best Original Score, 2007",
    trivia: "Kate Winslet's cottage set was so beloved by fans it inspired a wave of UK holiday-cottage tourism.",
    poster: "linear-gradient(160deg,#3a2a1e,#e5c14a)"
  },
  {
    id: "27-dresses",
    title: "27 Dresses",
    year: 2008,
    decade: "2000s",
    runtime: 111,
    director: "Anne Fletcher",
    writer: "Aline Brosh McKenna",
    cast: ["Katherine Heigl", "James Marsden", "Malin Åkerman"],
    genres: ["Romance", "Comedy"],
    tropes: ["Wedding", "Enemies to Lovers"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A perpetual bridesmaid who plans everyone's wedding but her own meets a cynical journalist writing about her unusual habit.",
    awards: "Nominated — Teen Choice Award, 2008",
    trivia: "Katherine Heigl actually wore all 27 dresses featured across the film's title sequence.",
    poster: "linear-gradient(160deg,#5b2a3e,#e5c14a)"
  },
  {
    id: "500-days-of-summer",
    title: "(500) Days of Summer",
    year: 2009,
    decade: "2000s",
    runtime: 95,
    director: "Marc Webb",
    writer: "Scott Neustadter, Michael H. Weber",
    cast: ["Joseph Gordon-Levitt", "Zooey Deschanel", "Chloë Grace Moretz"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Friends to Lovers"],
    country: "USA",
    rating: 7.7,
    awardWinner: true,
    synopsis: "Told out of order across 500 days, a hopeless romantic reflects on the relationship — and heartbreak — that reshaped how he sees love.",
    awards: "Golden Globe Nominee — Best Motion Picture, Comedy, 2010",
    trivia: "The film is deliberately structured as an anti-romantic-comedy, subverting genre expectations about happy endings.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "crazy-stupid-love",
    title: "Crazy, Stupid, Love.",
    year: 2011,
    decade: "2010s",
    runtime: 118,
    director: "Glenn Ficarra, John Requa",
    writer: "Dan Fogelman",
    cast: ["Steve Carell", "Ryan Gosling", "Emma Stone", "Julianne Moore"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance", "Love Triangle"],
    country: "USA",
    rating: 7.4,
    awardWinner: false,
    synopsis: "A recently divorced man gets a crash course in dating from a suave bachelor, while his family's romantic lives quietly intertwine in unexpected ways.",
    awards: "Nominated — Writers Guild Award, 2012",
    trivia: "Ryan Gosling trained intensively to achieve the physique for his character's much-discussed shirtless scene.",
    poster: "linear-gradient(160deg,#2a1e3a,#d1495b)"
  },
  {
    id: "silver-linings",
    title: "Silver Linings Playbook",
    year: 2012,
    decade: "2010s",
    runtime: 122,
    director: "David O. Russell",
    writer: "David O. Russell",
    cast: ["Bradley Cooper", "Jennifer Lawrence", "Robert De Niro"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance", "Friends to Lovers"],
    country: "USA",
    rating: 7.7,
    awardWinner: true,
    synopsis: "Two people navigating mental health struggles form an unlikely bond that helps them both begin to heal — and maybe fall in love.",
    awards: "Academy Award — Best Actress, 2013",
    trivia: "Jennifer Lawrence was only 22 when she won the Oscar for this role, one of the youngest Best Actress winners.",
    poster: "linear-gradient(160deg,#3a1e2a,#5b7fa6)"
  },
  {
    id: "about-time",
    title: "About Time",
    year: 2013,
    decade: "2010s",
    runtime: 123,
    director: "Richard Curtis",
    writer: "Richard Curtis",
    cast: ["Domhnall Gleeson", "Rachel McAdams", "Bill Nighy"],
    genres: ["Romance", "Comedy", "Fantasy"],
    tropes: ["Second Chance"],
    country: "UK",
    rating: 7.8,
    awardWinner: false,
    synopsis: "A young man discovers he can travel through time and sets out to use it to find love — only to learn the greater value of the ordinary days already lived.",
    awards: "Nominated — Saturn Award for Best Fantasy Film, 2014",
    trivia: "Richard Curtis has said he intended this as his final romantic comedy as a director.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "crazy-rich-asians",
    title: "Crazy Rich Asians",
    year: 2018,
    decade: "2010s",
    runtime: 121,
    director: "Jon M. Chu",
    writer: "Peter Chiarelli, Adele Lim",
    cast: ["Constance Wu", "Henry Golding", "Michelle Yeoh"],
    genres: ["Romance", "Comedy"],
    tropes: ["Wedding", "Fake Dating"],
    country: "USA",
    rating: 6.9,
    awardWinner: true,
    synopsis: "A New York economics professor travels to Singapore to meet her boyfriend's family, only to discover they're among the wealthiest in Asia.",
    awards: "Golden Globe Nominee — Best Motion Picture, Comedy, 2019",
    trivia: "It was the first major Hollywood studio film with a majority Asian cast in a contemporary setting in 25 years.",
    poster: "linear-gradient(160deg,#5b2a6e,#e5c14a)"
  },
  {
    id: "to-all-the-boys",
    title: "To All the Boys I've Loved Before",
    year: 2018,
    decade: "2010s",
    runtime: 99,
    director: "Susan Johnson",
    writer: "Sofia Alvarez",
    cast: ["Lana Condor", "Noah Centineo", "Janel Parrish"],
    genres: ["Romance", "Comedy", "Teen"],
    tropes: ["Fake Dating"],
    country: "USA",
    rating: 7.1,
    awardWinner: false,
    synopsis: "When secret love letters are mysteriously mailed to five boys, a teenager fakes a relationship with one of them to cover her tracks.",
    awards: "Teen Choice Award — Choice Movie, 2019",
    trivia: "Based on Jenny Han's bestselling novel, it became one of Netflix's most-rewatched original films.",
    poster: "linear-gradient(160deg,#3a1e2a,#d1495b)"
  },
  {
    id: "always-be-my-maybe",
    title: "Always Be My Maybe",
    year: 2019,
    decade: "2010s",
    runtime: 102,
    director: "Nahnatchka Khan",
    writer: "Ali Wong, Randall Park, Michael Golamco",
    cast: ["Ali Wong", "Randall Park", "Keanu Reeves"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers", "Second Chance"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "Childhood best friends reconnect as adults after years apart, testing whether their old bond can survive who they've each become.",
    awards: "Nominated — Satellite Award, 2019",
    trivia: "Keanu Reeves' self-parodying cameo was largely improvised and became the film's most quoted sequence.",
    poster: "linear-gradient(160deg,#1e3a2a,#e5c14a)"
  },
  {
    id: "palm-springs",
    title: "Palm Springs",
    year: 2020,
    decade: "2020s",
    runtime: 90,
    director: "Max Barbakow",
    writer: "Andy Siara",
    cast: ["Andy Samberg", "Cristin Milioti", "J.K. Simmons"],
    genres: ["Romance", "Comedy", "Sci-Fi"],
    tropes: ["Wedding", "Second Chance"],
    country: "USA",
    rating: 7.4,
    awardWinner: true,
    synopsis: "Two wedding guests find themselves stuck reliving the same day in an infinite time loop, and slowly fall for each other amid the chaos.",
    awards: "Independent Spirit Award — Best First Screenplay, 2021",
    trivia: "It set a Sundance sales record, partly funded by a stunt guaranteeing a refund if the buyer wasn't satisfied.",
    poster: "linear-gradient(160deg,#5b3a1e,#d1495b)"
  },
  {
    id: "the-half-of-it",
    title: "The Half of It",
    year: 2020,
    decade: "2020s",
    runtime: 104,
    director: "Alice Wu",
    writer: "Alice Wu",
    cast: ["Leah Lewis", "Daniel Diemer", "Alexxis Lemire"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Love Triangle", "Friends to Lovers"],
    country: "USA",
    rating: 7.0,
    awardWinner: false,
    synopsis: "A shy, brilliant student is paid to write love letters for a well-meaning jock, only to develop unexpected feelings for the girl herself.",
    awards: "Nominated — GLAAD Media Award, 2021",
    trivia: "Loosely inspired by Cyrano de Bergerac, reframed through a quietly queer coming-of-age lens.",
    poster: "linear-gradient(160deg,#1e2a3a,#3d6ea5)"
  },
  {
    id: "ticket-to-paradise",
    title: "Ticket to Paradise",
    year: 2022,
    decade: "2020s",
    runtime: 104,
    director: "Ol Parker",
    writer: "Ol Parker, Daniel Pipski",
    cast: ["George Clooney", "Julia Roberts", "Kaitlyn Dever"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Wedding"],
    country: "USA",
    rating: 6.3,
    awardWinner: false,
    synopsis: "Divorced exes reunite and reluctantly team up to stop their daughter from making the same marital mistake they did, on a tropical island getaway.",
    awards: "Nominated — People's Choice Award, 2022",
    trivia: "George Clooney and Julia Roberts had not shared the screen since Money Monster in 2016.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "anyone-but-you",
    title: "Anyone But You",
    year: 2023,
    decade: "2020s",
    runtime: 103,
    director: "Will Gluck",
    writer: "Ilana Wolpert, Will Gluck",
    cast: ["Sydney Sweeney", "Glen Powell", "Alexandra Shipp"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Fake Dating", "Wedding"],
    country: "USA",
    rating: 6.7,
    awardWinner: false,
    synopsis: "After a disastrous first date, two strangers are forced to pretend to be a couple at a destination wedding in Australia.",
    awards: "Nominated — People's Choice Award, 2024",
    trivia: "Loosely inspired by Shakespeare's Much Ado About Nothing, the film became a sleeper box-office hit driven by social media.",
    poster: "linear-gradient(160deg,#3a1e1e,#e5c14a)"
  },
  {
    id: "the-idea-of-you",
    title: "The Idea of You",
    year: 2024,
    decade: "2020s",
    runtime: 115,
    director: "Michael Showalter",
    writer: "Jennifer Westfeldt, Michael Showalter",
    cast: ["Anne Hathaway", "Nicholas Galitzianakis", "Ella Rubin"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 7.0,
    awardWinner: false,
    synopsis: "A single mother in her forties falls into an unexpected romance with the much younger lead singer of a boy band, upending both their lives.",
    awards: "Nominated — MTV Movie Award, 2024",
    trivia: "Based on Robinne Lee's 2017 novel, reportedly inspired by real celebrity boy-band culture.",
    poster: "linear-gradient(160deg,#2a1e3a,#d1495b)"
  },
  {
    id: "starlight-and-static",
    title: "Starlight and Static",
    year: 2026,
    decade: "2020s",
    runtime: 108,
    director: "Reina Achebe",
    writer: "Reina Achebe, Tom Farley",
    cast: ["Simone Ashley", "Percy Hynes White", "Awkwafina"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Workplace Romance"],
    country: "USA",
    rating: 7.2,
    awardWinner: false,
    synopsis: "A veteran radio DJ and the podcast prodigy sent to replace her are ordered to co-host a late-night show — and to their mutual horror, it works.",
    awards: "Nominated — Independent Spirit Award, 2026",
    trivia: "Filmed largely inside a single working radio station to preserve the show's live, one-take on-air chemistry.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "when-harry-met-sally",
    title: "When Harry Met Sally...",
    year: 1990,
    decade: "1990s",
    runtime: 96,
    director: "Rob Reiner",
    writer: "Nora Ephron",
    cast: ["Billy Crystal", "Meg Ryan", "Carrie Fisher"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers"],
    country: "USA",
    rating: 7.6,
    awardWinner: true,
    synopsis: "Two friends who've sworn romance would ruin everything spend twelve years proving themselves wrong.",
    awards: "Nominated — Academy Award for Best Original Screenplay, 1990",
    trivia: "The famous deli scene was reportedly shot in a single afternoon with a real customer delivering the punchline.",
    poster: "linear-gradient(160deg,#3a2a1e,#e5c14a)"
  },
  {
    id: "green-card",
    title: "Green Card",
    year: 1990,
    decade: "1990s",
    runtime: 108,
    director: "Peter Weir",
    writer: "Peter Weir",
    cast: ["Gérard Depardieu", "Andie MacDowell", "Bebe Neuwirth"],
    genres: ["Romance", "Comedy"],
    tropes: ["Marriage of Convenience"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "A marriage of convenience for a green card slowly turns into something neither party bargained for.",
    awards: "Nominated — Golden Globe for Best Actor, 1991",
    trivia: "Gérard Depardieu learned much of his English dialogue phonetically for the role.",
    poster: "linear-gradient(160deg,#1e3a2a,#3d6ea5)"
  },
  {
    id: "lm-marriage-story-comedy-placeholder",
    title: "L.A. Story",
    year: 1991,
    decade: "1990s",
    runtime: 95,
    director: "Mick Jackson",
    writer: "Steve Martin",
    cast: ["Steve Martin", "Victoria Tennant", "Sarah Jessica Parker"],
    genres: ["Romance", "Comedy", "Fantasy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.9,
    awardWinner: false,
    synopsis: "A whimsical LA weatherman gets relationship advice from a freeway billboard while sorting out two very different women.",
    awards: "Nominated — Writers Guild Award, 1992",
    trivia: "Steve Martin wrote the screenplay as a satirical love letter to Los Angeles culture.",
    poster: "linear-gradient(160deg,#5b3a1e,#d1495b)"
  },
  {
    id: "my-cousin-vinny-placeholder",
    title: "Only You",
    year: 1994,
    decade: "1990s",
    runtime: 108,
    director: "Norman Jewison",
    writer: "Diane Drake",
    cast: ["Marisa Tomei", "Robert Downey Jr.", "Bonnie Hunt"],
    genres: ["Romance", "Comedy"],
    tropes: ["Road Trip", "Second Chance"],
    country: "USA",
    rating: 6.3,
    awardWinner: false,
    synopsis: "A woman convinced a childhood fortune-teller's prophecy names her soulmate chases a stranger across Italy.",
    awards: "Nominated — ASCAP Film Award, 1995",
    trivia: "Much of the film was shot on location in Venice and Rome to heighten its fairy-tale romance feel.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "forget-paris",
    title: "Forget Paris",
    year: 1995,
    decade: "1990s",
    runtime: 101,
    director: "Billy Crystal",
    writer: "Billy Crystal, Lowell Ganz, Babaloo Mandel",
    cast: ["Billy Crystal", "Debra Winger", "Joe Mantegna"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.3,
    awardWinner: false,
    synopsis: "A referee and an airline employee fall in love in Paris, then must figure out how to keep it alive back home.",
    awards: "Nominated — ASCAP Film Award, 1996",
    trivia: "The film's framing device — friends trading the story over dinner — was added late in the writing process.",
    poster: "linear-gradient(160deg,#2a3a1e,#d1495b)"
  },
  {
    id: "while-you-were-sleeping",
    title: "While You Were Sleeping",
    year: 1995,
    decade: "1990s",
    runtime: 103,
    director: "Jon Turteltaub",
    writer: "Daniel G. Sullivan, Fredric Lebow",
    cast: ["Sandra Bullock", "Bill Pullman", "Peter Gallagher"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Fake Dating"],
    country: "USA",
    rating: 6.9,
    awardWinner: false,
    synopsis: "A lonely transit worker is mistaken for the fiancée of a man in a coma, and finds herself falling for his brother instead.",
    awards: "Nominated — MTV Movie Award, 1996",
    trivia: "Sandra Bullock's performance is widely credited with launching her as a leading romantic-comedy star.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "sabrina-1995",
    title: "Sabrina",
    year: 1995,
    decade: "1990s",
    runtime: 127,
    director: "Sydney Pollack",
    writer: "Barbara Benedek, David Rayfiel",
    cast: ["Harrison Ford", "Julia Ormond", "Greg Kinnear"],
    genres: ["Romance", "Comedy"],
    tropes: ["Love Triangle", "Second Chance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A chauffeur's daughter returns from Paris transformed, catching the eye of both sons of the wealthy family her father serves.",
    awards: "Nominated — Golden Globe for Best Actress, 1996",
    trivia: "A remake of the 1954 Billy Wilder classic of the same name.",
    poster: "linear-gradient(160deg,#3a2a1e,#5b7fa6)"
  },
  {
    id: "the-truth-about-cats-and-dogs",
    title: "The Truth About Cats & Dogs",
    year: 1996,
    decade: "1990s",
    runtime: 97,
    director: "Michael Lehmann",
    writer: "Audrey Wells",
    cast: ["Janeane Garofalo", "Uma Thurman", "Ben Chaplin"],
    genres: ["Romance", "Comedy"],
    tropes: ["Love Triangle", "Fake Dating"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A radio vet asks her glamorous neighbor to stand in for her on a date, tangling three people in a case of mistaken identity.",
    awards: "Nominated — MTV Movie Award, 1997",
    trivia: "Loosely inspired by the classic structure of Cyrano de Bergerac.",
    poster: "linear-gradient(160deg,#5b2a3e,#3d6ea5)"
  },
  {
    id: "my-best-friends-wedding",
    title: "My Best Friend's Wedding",
    year: 1997,
    decade: "1990s",
    runtime: 105,
    director: "P.J. Hogan",
    writer: "Ronald Bass",
    cast: ["Julia Roberts", "Dermot Mulroney", "Cameron Diaz", "Rupert Everett"],
    genres: ["Romance", "Comedy"],
    tropes: ["Wedding", "Friends to Lovers"],
    country: "USA",
    rating: 6.7,
    awardWinner: false,
    synopsis: "A food critic realizes she's in love with her best friend just days before his wedding to someone else, and schemes to win him back.",
    awards: "Nominated — Golden Globe for Best Actress, 1998",
    trivia: "The film deliberately subverts the genre by not giving its heroine the traditional happy ending.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "as-good-as-it-gets",
    title: "As Good as It Gets",
    year: 1997,
    decade: "1990s",
    runtime: 139,
    director: "James L. Brooks",
    writer: "Mark Andrus, James L. Brooks",
    cast: ["Jack Nicholson", "Helen Hunt", "Greg Kinnear"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 7.4,
    awardWinner: true,
    synopsis: "A misanthropic writer with obsessive tendencies finds his rigid world upended by a waitress and her sick son.",
    awards: "Academy Award — Best Actor and Best Actress, 1998",
    trivia: "It remains one of only a handful of films to sweep both lead acting Oscars in the same year.",
    poster: "linear-gradient(160deg,#2a2a2a,#e5c14a)"
  },
  {
    id: "shakespeare-in-love",
    title: "Shakespeare in Love",
    year: 1998,
    decade: "1990s",
    runtime: 123,
    director: "John Madden",
    writer: "Marc Norman, Tom Stoppard",
    cast: ["Gwyneth Paltrow", "Joseph Fiennes", "Judi Dench"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance"],
    country: "UK",
    rating: 7.1,
    awardWinner: true,
    synopsis: "A young William Shakespeare, stuck with writer's block, finds his muse in a noblewoman secretly determined to act in his plays.",
    awards: "Academy Award — Best Picture, 1999",
    trivia: "Its Best Picture win over Saving Private Ryan remains one of the most debated Oscar upsets.",
    poster: "linear-gradient(160deg,#3a2a1e,#e5c14a)"
  },
  {
    id: "the-parent-trap-1998",
    title: "The Parent Trap",
    year: 1998,
    decade: "1990s",
    runtime: 128,
    director: "Nancy Meyers",
    writer: "Nancy Meyers, Charles Shyer",
    cast: ["Lindsay Lohan", "Dennis Quaid", "Natasha Richardson"],
    genres: ["Comedy", "Romance", "Family"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.7,
    awardWinner: false,
    synopsis: "Twins separated at birth meet at summer camp and scheme to reunite their divorced parents.",
    awards: "Nominated — Young Artist Award, 1999",
    trivia: "Lindsay Lohan played both twins using early split-screen and motion-control camera techniques.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "runaway-bride",
    title: "Runaway Bride",
    year: 1999,
    decade: "1990s",
    runtime: 116,
    director: "Garry Marshall",
    writer: "Josann McGibbon, Sara Parriott",
    cast: ["Julia Roberts", "Richard Gere", "Joan Cusack"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Wedding"],
    country: "USA",
    rating: 6.1,
    awardWinner: false,
    synopsis: "A columnist sent to profile a woman famous for leaving grooms at the altar finds himself falling for his subject.",
    awards: "Nominated — People's Choice Award, 2000",
    trivia: "It reunited Julia Roberts and Richard Gere nearly a decade after Pretty Woman.",
    poster: "linear-gradient(160deg,#5b2a3e,#e5c14a)"
  },
  {
    id: "never-been-kissed",
    title: "Never Been Kissed",
    year: 1999,
    decade: "1990s",
    runtime: 107,
    director: "Raja Gosnell",
    writer: "Abby Kohn, Marc Silverstein",
    cast: ["Drew Barrymore", "David Arquette", "Michael Vartan"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.1,
    awardWinner: false,
    synopsis: "A journalist goes undercover in high school for a story and gets a second chance at the popularity — and romance — that eluded her the first time.",
    awards: "Nominated — Blockbuster Entertainment Award, 2000",
    trivia: "Drew Barrymore also produced the film through her company Flower Films.",
    poster: "linear-gradient(160deg,#3a1e1e,#e5c14a)"
  },
  {
    id: "drive-me-crazy",
    title: "Drive Me Crazy",
    year: 1999,
    decade: "1990s",
    runtime: 91,
    director: "John Schultz",
    writer: "Rob Thomas",
    cast: ["Melissa Joan Hart", "Adrian Grenier", "Susan May Pratt"],
    genres: ["Comedy", "Romance", "Teen"],
    tropes: ["Friends to Lovers", "Fake Dating"],
    country: "USA",
    rating: 5.7,
    awardWinner: false,
    synopsis: "Former childhood friends now on opposite social paths team up as fake dates for a school dance, only to catch real feelings.",
    awards: "Nominated — Teen Choice Award, 2000",
    trivia: "The soundtrack, featuring Britney Spears' cover of 'I Love Rock 'n' Roll', became more famous than the film itself.",
    poster: "linear-gradient(160deg,#2a3a1e,#e5c14a)"
  },
  {
    id: "bridget-jones-diary",
    title: "Bridget Jones's Diary",
    year: 2001,
    decade: "2000s",
    runtime: 97,
    director: "Sharon Maguire",
    writer: "Helen Fielding, Andrew Davies, Richard Curtis",
    cast: ["Renée Zellweger", "Colin Firth", "Hugh Grant"],
    genres: ["Romance", "Comedy"],
    tropes: ["Love Triangle", "Second Chance"],
    country: "UK",
    rating: 6.7,
    awardWinner: false,
    synopsis: "A thirty-something Londoner resolves to get her life together, chronicling every mishap and romantic entanglement along the way.",
    awards: "Nominated — Academy Award for Best Actress, 2002",
    trivia: "Renée Zellweger, an American, kept a British accent for months during filming, including off-camera.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "kate-and-leopold",
    title: "Kate & Leopold",
    year: 2001,
    decade: "2000s",
    runtime: 118,
    director: "James Mangold",
    writer: "James Mangold, Steven Rogers",
    cast: ["Meg Ryan", "Hugh Jackman", "Liev Schreiber"],
    genres: ["Romance", "Comedy", "Fantasy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A 19th-century duke falls through a time portal into modern New York City and into the life of a driven advertising executive.",
    awards: "Nominated — Academy Award for Best Original Screenplay, 2002",
    trivia: "Hugh Jackman trained in period etiquette and dance to sell the character's old-world manners.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "sweet-home-alabama",
    title: "Sweet Home Alabama",
    year: 2002,
    decade: "2000s",
    runtime: 108,
    director: "Andy Tennant",
    writer: "C. Jay Cox",
    cast: ["Reese Witherspoon", "Josh Lucas", "Patrick Dempsey"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Love Triangle"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "A rising New York fashion designer must return to her small Alabama hometown to finalize a divorce she's kept secret from her new fiancé.",
    awards: "Nominated — Teen Choice Award, 2003",
    trivia: "The lightning-glass field featured in the film was built specifically for the production.",
    poster: "linear-gradient(160deg,#3a2a1e,#3d6ea5)"
  },
  {
    id: "maid-in-manhattan",
    title: "Maid in Manhattan",
    year: 2002,
    decade: "2000s",
    runtime: 105,
    director: "Wayne Wang",
    writer: "Kevin Wade",
    cast: ["Jennifer Lopez", "Ralph Fiennes", "Natasha Richardson"],
    genres: ["Romance", "Comedy"],
    tropes: ["Fake Dating", "Workplace Romance"],
    country: "USA",
    rating: 5.6,
    awardWinner: false,
    synopsis: "A hotel maid is mistaken for a wealthy guest by a politician staying at the hotel, and the misunderstanding sparks an unlikely romance.",
    awards: "Nominated — Teen Choice Award, 2003",
    trivia: "A modern riff on the Cinderella story, deliberately set against the backdrop of a working-class New York City.",
    poster: "linear-gradient(160deg,#5b2a6e,#d1495b)"
  },
  {
    id: "two-weeks-notice",
    title: "Two Weeks Notice",
    year: 2002,
    decade: "2000s",
    runtime: 101,
    director: "Marc Lawrence",
    writer: "Marc Lawrence",
    cast: ["Sandra Bullock", "Hugh Grant", "Alicia Witt"],
    genres: ["Romance", "Comedy"],
    tropes: ["Workplace Romance", "Enemies to Lovers"],
    country: "USA",
    rating: 6.1,
    awardWinner: false,
    synopsis: "An idealistic lawyer working for a careless real-estate mogul quits, forcing him to realize how much he depends on her — for more than legal advice.",
    awards: "Nominated — Teen Choice Award, 2003",
    trivia: "Sandra Bullock also produced the film through her company Fortis Films.",
    poster: "linear-gradient(160deg,#2a2a2a,#e5c14a)"
  },
  {
    id: "love-and-basketball-note",
    title: "Just Married",
    year: 2003,
    decade: "2000s",
    runtime: 95,
    director: "Shawn Levy",
    writer: "Sam Harper",
    cast: ["Ashton Kutcher", "Brittany Murphy", "Christian Kane"],
    genres: ["Romance", "Comedy"],
    tropes: ["Road Trip"],
    country: "USA",
    rating: 5.7,
    awardWinner: false,
    synopsis: "A newlywed couple's disastrous honeymoon threatens to end their marriage before it's even begun.",
    awards: "Nominated — Teen Choice Award, 2003",
    trivia: "Most of the destructive hotel-room sequence was filmed practically rather than with visual effects.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "love-actually-companion",
    title: "Bringing Down the House",
    year: 2003,
    decade: "2000s",
    runtime: 105,
    director: "Adam Shankman",
    writer: "Jason Filardi",
    cast: ["Steve Martin", "Queen Latifah", "Eugene Levy"],
    genres: ["Comedy", "Romance"],
    tropes: ["Enemies to Lovers"],
    country: "USA",
    rating: 5.5,
    awardWinner: false,
    synopsis: "A buttoned-up divorce lawyer's online date turns out to be an escaped convict determined to prove her innocence — and upend his tidy life.",
    awards: "Nominated — NAACP Image Award, 2004",
    trivia: "It was one of the highest-grossing films of 2003 despite mixed reviews.",
    poster: "linear-gradient(160deg,#1e3a2a,#e5c14a)"
  },
  {
    id: "win-a-date-with-tad-hamilton",
    title: "Win a Date with Tad Hamilton!",
    year: 2004,
    decade: "2000s",
    runtime: 96,
    director: "Robert Luketic",
    writer: "Victor Levin",
    cast: ["Kate Bosworth", "Topher Grace", "Josh Duhamel"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers", "Love Triangle"],
    country: "USA",
    rating: 5.7,
    awardWinner: false,
    synopsis: "A small-town grocery clerk wins a date with a Hollywood heartthrob, forcing her best friend to finally admit his feelings.",
    awards: "Nominated — Teen Choice Award, 2004",
    trivia: "The film's small-town set was built on a working studio backlot in North Carolina.",
    poster: "linear-gradient(160deg,#3a2a1e,#d1495b)"
  },
  {
    id: "the-wedding-date",
    title: "The Wedding Date",
    year: 2005,
    decade: "2000s",
    runtime: 89,
    director: "Clare Kilner",
    writer: "Dana Fox",
    cast: ["Debra Messing", "Dermot Mulroney", "Amy Adams"],
    genres: ["Romance", "Comedy"],
    tropes: ["Fake Dating", "Wedding"],
    country: "USA",
    rating: 6.0,
    awardWinner: false,
    synopsis: "A woman hires an escort to pose as her boyfriend at her sister's London wedding, where her ex will also be a guest.",
    awards: "Nominated — Teen Choice Award, 2005",
    trivia: "Based on the novel Asking for Trouble by Elizabeth Young.",
    poster: "linear-gradient(160deg,#5b2a3e,#3d6ea5)"
  },
  {
    id: "must-love-dogs",
    title: "Must Love Dogs",
    year: 2005,
    decade: "2000s",
    runtime: 98,
    director: "Gary David Goldberg",
    writer: "Gary David Goldberg",
    cast: ["Diane Lane", "John Cusack", "Elizabeth Perkins"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 5.9,
    awardWinner: false,
    synopsis: "A recently divorced preschool teacher is pushed back into the dating pool by her well-meaning family, with mixed and comic results.",
    awards: "Nominated — Teen Choice Award, 2005",
    trivia: "Based on the novel of the same name by Claire Cook.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "failure-to-launch",
    title: "Failure to Launch",
    year: 2006,
    decade: "2000s",
    runtime: 97,
    director: "Tom Dey",
    writer: "Tom J. Astle, Matt Ember",
    cast: ["Matthew McConaughey", "Sarah Jessica Parker", "Zooey Deschanel"],
    genres: ["Romance", "Comedy"],
    tropes: ["Fake Dating", "Second Chance"],
    country: "USA",
    rating: 5.8,
    awardWinner: false,
    synopsis: "Parents hire a professional 'interventionist' to seduce their thirty-something son into finally moving out — and she falls for him instead.",
    awards: "Nominated — Teen Choice Award, 2006",
    trivia: "The film's premise inspired real conversations at the time about the trend of adult children living at home.",
    poster: "linear-gradient(160deg,#3a1e1e,#3d6ea5)"
  },
  {
    id: "the-break-up",
    title: "The Break-Up",
    year: 2006,
    decade: "2000s",
    runtime: 106,
    director: "Peyton Reed",
    writer: "Jeremy Garelick, Jay Lavender",
    cast: ["Vince Vaughn", "Jennifer Aniston", "Jon Favreau"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.0,
    awardWinner: false,
    synopsis: "A couple splits up but refuses to move out of their shared condo, waging a slow-motion war neither truly wants to win.",
    awards: "Nominated — Teen Choice Award, 2006",
    trivia: "Its notably unresolved, bittersweet ending was a deliberate departure from typical genre convention.",
    poster: "linear-gradient(160deg,#2a2a2a,#d1495b)"
  },
  {
    id: "the-proposal",
    title: "The Proposal",
    year: 2009,
    decade: "2000s",
    runtime: 108,
    director: "Anne Fletcher",
    writer: "Pete Chiarelli",
    cast: ["Sandra Bullock", "Ryan Reynolds", "Betty White"],
    genres: ["Romance", "Comedy"],
    tropes: ["Marriage of Convenience", "Fake Dating"],
    country: "USA",
    rating: 6.6,
    awardWinner: false,
    synopsis: "A demanding editor facing deportation forces her assistant into a fake engagement, and drags him home to Alaska to sell the lie to his family.",
    awards: "Nominated — People's Choice Award, 2010",
    trivia: "The Alaska scenes were largely filmed on the Massachusetts coast standing in for the Pacific Northwest.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "the-ugly-truth",
    title: "The Ugly Truth",
    year: 2009,
    decade: "2000s",
    runtime: 96,
    director: "Robert Luketic",
    writer: "Nicole Eastman",
    cast: ["Katherine Heigl", "Gerard Butler", "Bree Turner"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Workplace Romance"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A TV producer with idealistic notions of love is paired on-air with a cynical relationship expert who insists chemistry is just biology.",
    awards: "Nominated — Teen Choice Award, 2009",
    trivia: "Gerard Butler also served as a producer on the film.",
    poster: "linear-gradient(160deg,#3a1e2a,#d1495b)"
  },
  {
    id: "leap-year",
    title: "Leap Year",
    year: 2010,
    decade: "2010s",
    runtime: 100,
    director: "Anand Tucker",
    writer: "Deborah Kaplan, Harry Elfont",
    cast: ["Amy Adams", "Matthew Goode", "Adam Scott"],
    genres: ["Romance", "Comedy"],
    tropes: ["Road Trip", "Enemies to Lovers"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A woman travels to Ireland to propose to her boyfriend on Leap Day tradition, and finds her trip — and heart — redirected by a grumpy innkeeper.",
    awards: "Nominated — Teen Choice Award, 2010",
    trivia: "Filmed extensively on location across the Irish countryside, including County Wicklow.",
    poster: "linear-gradient(160deg,#1e3a2a,#3d6ea5)"
  },
  {
    id: "friends-with-benefits",
    title: "Friends with Benefits",
    year: 2011,
    decade: "2010s",
    runtime: 109,
    director: "Will Gluck",
    writer: "Keith Merryman, David A. Newman, Will Gluck",
    cast: ["Justin Timberlake", "Mila Kunis", "Patricia Clarkson"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers"],
    country: "USA",
    rating: 6.6,
    awardWinner: false,
    synopsis: "Two friends agree to keep sex and feelings separate, a plan that predictably — and comedically — falls apart.",
    awards: "Nominated — Teen Choice Award, 2011",
    trivia: "The film knowingly pokes fun at romantic-comedy tropes throughout its own script.",
    poster: "linear-gradient(160deg,#3a2a1e,#e5c14a)"
  },
  {
    id: "what-if",
    title: "What If",
    year: 2013,
    decade: "2010s",
    runtime: 102,
    director: "Michael Dowse",
    writer: "Elan Mastai",
    cast: ["Daniel Radcliffe", "Zoe Kazan", "Adam Driver"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers"],
    country: "Canada",
    rating: 6.8,
    awardWinner: false,
    synopsis: "A medical school dropout and an animator become close friends, both determined not to ruin things by admitting they're falling for each other.",
    awards: "Nominated — Canadian Screen Award, 2014",
    trivia: "Originally titled The F Word before a theatrical rebrand for wider release.",
    poster: "linear-gradient(160deg,#1e2a3a,#d1495b)"
  },
  {
    id: "trainwreck",
    title: "Trainwreck",
    year: 2015,
    decade: "2010s",
    runtime: 125,
    director: "Judd Apatow",
    writer: "Amy Schumer",
    cast: ["Amy Schumer", "Bill Hader", "Brie Larson"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.2,
    awardWinner: false,
    synopsis: "A commitment-averse magazine writer is thrown when she genuinely falls for the sports doctor she was supposed to be profiling.",
    awards: "Nominated — Writers Guild Award, 2016",
    trivia: "Amy Schumer wrote the semi-autobiographical script before she was a household name.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "the-big-sick",
    title: "The Big Sick",
    year: 2017,
    decade: "2010s",
    runtime: 120,
    director: "Michael Showalter",
    writer: "Emily V. Gordon, Kumail Nanjiani",
    cast: ["Kumail Nanjiani", "Zoe Kazan", "Holly Hunter", "Ray Romano"],
    genres: ["Romance", "Comedy", "Drama"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 7.5,
    awardWinner: true,
    synopsis: "A Pakistani-American comedian's budding relationship is tested when his girlfriend falls into a medically induced coma, forcing him to face both cultures' expectations at once.",
    awards: "Nominated — Academy Award for Best Original Screenplay, 2018",
    trivia: "Based on the real-life courtship of the film's writers, Kumail Nanjiani and Emily V. Gordon.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "set-it-up",
    title: "Set It Up",
    year: 2018,
    decade: "2010s",
    runtime: 105,
    director: "Claire Scanlon",
    writer: "Katie Silberman",
    cast: ["Zoey Deutch", "Glen Powell", "Lucy Liu"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers", "Fake Dating"],
    country: "USA",
    rating: 6.7,
    awardWinner: false,
    synopsis: "Two overworked assistants scheme to set up their demanding bosses so they'll have less work — and fewer excuses not to fall for each other themselves.",
    awards: "Nominated — Teen Choice Award, 2018",
    trivia: "Filmed largely across New York City to lean into its modern-workplace rom-com identity.",
    poster: "linear-gradient(160deg,#2a1e3a,#e5c14a)"
  },
  {
    id: "crazy-rich-asians-companion",
    title: "The Kissing Booth",
    year: 2018,
    decade: "2010s",
    runtime: 105,
    director: "Vince Marcello",
    writer: "Vince Marcello",
    cast: ["Joey King", "Jacob Elordi", "Joel Courtney"],
    genres: ["Romance", "Comedy", "Teen"],
    tropes: ["Friends to Lovers", "Enemies to Lovers"],
    country: "USA",
    rating: 6.1,
    awardWinner: false,
    synopsis: "A teenager's first kiss with her best friend's older brother at a school fundraiser upends the rules that have protected their friendship for years.",
    awards: "Nominated — Teen Choice Award, 2019",
    trivia: "Based on a Wattpad novel written by author Beth Reekles as a teenager herself.",
    poster: "linear-gradient(160deg,#3a1e2a,#d1495b)"
  },
  {
    id: "isnt-it-romantic",
    title: "Isn't It Romantic",
    year: 2019,
    decade: "2010s",
    runtime: 89,
    director: "Todd Strauss-Schulson",
    writer: "Erin Cardillo, Dana Fox, Katie Silberman",
    cast: ["Rebel Wilson", "Liam Hemsworth", "Adam DeVine"],
    genres: ["Romance", "Comedy", "Fantasy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 5.7,
    awardWinner: false,
    synopsis: "A rom-com skeptic knocked unconscious wakes to find herself trapped inside a PG-13 romantic comedy, forced to live out every genre cliché she despises.",
    awards: "Nominated — Teen Choice Award, 2019",
    trivia: "The film was designed as a loving parody of romantic-comedy conventions from the inside.",
    poster: "linear-gradient(160deg,#5b2a6e,#d1495b)"
  },
  {
    id: "someone-great",
    title: "Someone Great",
    year: 2019,
    decade: "2010s",
    runtime: 92,
    director: "Jennifer Kaytin Robinson",
    writer: "Jennifer Kaytin Robinson",
    cast: ["Gina Rodriguez", "Brittany Snow", "DeWanda Wise"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Road Trip"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "After a painful breakup, a journalist spends one last wild day in New York with her two best friends before moving across the country.",
    awards: "Nominated — Teen Choice Award, 2019",
    trivia: "It became one of Netflix's most-watched original films within its first weekend of release.",
    poster: "linear-gradient(160deg,#1e2a3a,#e5c14a)"
  },
  {
    id: "the-lovebirds",
    title: "The Lovebirds",
    year: 2020,
    decade: "2020s",
    runtime: 87,
    director: "Michael Showalter",
    writer: "Aaron Abrams, Brendan Gall",
    cast: ["Issa Rae", "Kumail Nanjiani", "Paul Sparks"],
    genres: ["Romance", "Comedy", "Thriller"],
    tropes: ["Second Chance", "Road Trip"],
    country: "USA",
    rating: 6.0,
    awardWinner: false,
    synopsis: "A couple on the verge of breaking up gets pulled into a bizarre murder conspiracy over the course of one long, chaotic night.",
    awards: "Nominated — NAACP Image Award, 2021",
    trivia: "It was originally set for a theatrical release before shifting to streaming.",
    poster: "linear-gradient(160deg,#3a1e1e,#d1495b)"
  },
  {
    id: "the-broken-hearts-gallery",
    title: "The Broken Hearts Gallery",
    year: 2020,
    decade: "2020s",
    runtime: 108,
    director: "Natalie Krinsky",
    writer: "Natalie Krinsky",
    cast: ["Geraldine Viswanathan", "Dacre Montgomery", "Utkarsh Ambudkar"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A gallery assistant who keeps mementos from every breakup channels her heartbreak into a public exhibit for other people's lost loves.",
    awards: "Nominated — MTV Movie Award, 2021",
    trivia: "Writer-director Natalie Krinsky drew on her own habit of keeping breakup keepsakes for the premise.",
    poster: "linear-gradient(160deg,#5b3a1e,#e5c14a)"
  },
  {
    id: "happiest-season",
    title: "Happiest Season",
    year: 2020,
    decade: "2020s",
    runtime: 102,
    director: "Clea DuVall",
    writer: "Clea DuVall, Mary Holland",
    cast: ["Kristen Stewart", "Mackenzie Davis", "Alison Brie"],
    genres: ["Romance", "Comedy", "Holiday"],
    tropes: ["Holiday Romance", "Fake Dating"],
    country: "USA",
    rating: 6.1,
    awardWinner: false,
    synopsis: "A woman plans to propose to her girlfriend at a family Christmas gathering, only to learn her girlfriend hasn't come out to her conservative family.",
    awards: "Nominated — GLAAD Media Award, 2021",
    trivia: "It was one of the first major-studio holiday rom-coms centered on a same-sex couple.",
    poster: "linear-gradient(160deg,#1e3a3a,#d1495b)"
  },
  {
    id: "love-hard",
    title: "Love Hard",
    year: 2021,
    decade: "2020s",
    runtime: 110,
    director: "Hernán Jiménez",
    writer: "Danny Mackey, Rebecca Ewing",
    cast: ["Nina Dobrev", "Jimmy O. Yang", "Darren Barnet"],
    genres: ["Romance", "Comedy", "Holiday"],
    tropes: ["Fake Dating", "Holiday Romance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "A woman flies across the country to surprise her online match for Christmas, only to discover the photos she fell for weren't really his.",
    awards: "Nominated — People's Choice Award, 2022",
    trivia: "The film wears its Cyrano de Bergerac inspiration openly within its own dialogue.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "marry-me",
    title: "Marry Me",
    year: 2022,
    decade: "2020s",
    runtime: 112,
    director: "Kat Coiro",
    writer: "John Rogers, Tami Sagher, Harper Dill",
    cast: ["Jennifer Lopez", "Owen Wilson", "Maluma"],
    genres: ["Romance", "Comedy", "Musical"],
    tropes: ["Second Chance", "Fake Dating"],
    country: "USA",
    rating: 5.9,
    awardWinner: false,
    synopsis: "A pop superstar impulsively marries a stranger from the crowd after discovering her fiancé's infidelity moments before their televised wedding.",
    awards: "Nominated — People's Choice Award, 2022",
    trivia: "Based on a graphic novel of the same name by Bobby Crosby.",
    poster: "linear-gradient(160deg,#5b2a3e,#e5c14a)"
  },
  {
    id: "i-want-you-back",
    title: "I Want You Back",
    year: 2022,
    decade: "2020s",
    runtime: 115,
    director: "Jason Orley",
    writer: "Isaac Aptaker, Elizabeth Berger",
    cast: ["Charlie Day", "Jenny Slate", "Scott Eastwood"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 6.4,
    awardWinner: false,
    synopsis: "Two strangers freshly dumped by their partners team up to sabotage their exes' new relationships — and accidentally start one of their own.",
    awards: "Nominated — People's Choice Award, 2022",
    trivia: "It was one of Amazon Studios' most-streamed originals in its opening weekend.",
    poster: "linear-gradient(160deg,#1e2a3a,#3d6ea5)"
  },
  {
    id: "shotgun-wedding",
    title: "Shotgun Wedding",
    year: 2023,
    decade: "2020s",
    runtime: 100,
    director: "Jason Moore",
    writer: "Mark Hammer",
    cast: ["Jennifer Lopez", "Josh Duhamel", "Sonia Braga"],
    genres: ["Romance", "Comedy", "Action"],
    tropes: ["Wedding", "Second Chance"],
    country: "USA",
    rating: 5.9,
    awardWinner: false,
    synopsis: "A couple's destination wedding is thrown into chaos when armed criminals crash the ceremony, forcing the bride and groom to fight to save their guests — and their relationship.",
    awards: "Nominated — People's Choice Award, 2023",
    trivia: "The film blends the rom-com and action genres more overtly than most entries in the archive.",
    poster: "linear-gradient(160deg,#3a2a1e,#d1495b)"
  },
  {
    id: "rye-lane",
    title: "Rye Lane",
    year: 2023,
    decade: "2020s",
    runtime: 82,
    director: "Raine Allen-Miller",
    writer: "Nathan Bryon, Tom Melia",
    cast: ["David Jonsson", "Vivian Oparah", "Poppy Allen-Quarmby"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "UK",
    rating: 7.0,
    awardWinner: true,
    synopsis: "Two strangers, both nursing fresh heartbreak, spend a single whirlwind day wandering South London and talking each other back to life.",
    awards: "Nominated — BAFTA for Outstanding Debut, 2024",
    trivia: "Its distinctive fisheye cinematography was chosen to make ordinary South London streets feel heightened and romantic.",
    poster: "linear-gradient(160deg,#1e3a2a,#e5c14a)"
  },
  {
    id: "you-people",
    title: "You People",
    year: 2023,
    decade: "2020s",
    runtime: 117,
    director: "Kenya Barris",
    writer: "Kenya Barris, Jonah Hill",
    cast: ["Jonah Hill", "Lauren London", "Eddie Murphy", "Julia Louis-Dreyfus"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance"],
    country: "USA",
    rating: 5.8,
    awardWinner: false,
    synopsis: "A new couple's whirlwind romance collides with their families' very different expectations as an engagement approaches.",
    awards: "Nominated — NAACP Image Award, 2024",
    trivia: "Eddie Murphy and Julia Louis-Dreyfus play the disapproving parents on either side of the relationship.",
    poster: "linear-gradient(160deg,#2a1e3a,#e5c14a)"
  },
  {
    id: "players",
    title: "Players",
    year: 2024,
    decade: "2020s",
    runtime: 106,
    director: "Trish Sie",
    writer: "Whit Anderson",
    cast: ["Gina Rodriguez", "Damon Wayans Jr.", "Tom Ellis"],
    genres: ["Romance", "Comedy"],
    tropes: ["Friends to Lovers", "Enemies to Lovers"],
    country: "USA",
    rating: 5.4,
    awardWinner: false,
    synopsis: "A sports reporter who runs a friend group's playbook for casual dating breaks her own rules when she falls for the plan's newest target.",
    awards: "Nominated — People's Choice Award, 2024",
    trivia: "The production filmed on location around New York City sports venues to ground its journalism setting.",
    poster: "linear-gradient(160deg,#3a1e2a,#3d6ea5)"
  },
  {
    id: "my-favorite-holiday-mix",
    title: "A Merry Scottish Christmas",
    year: 2024,
    decade: "2020s",
    runtime: 98,
    director: "Ernie Barbarash",
    writer: "Julie Sherman Wolfe",
    cast: ["Cindy Busby", "Ben Lamb", "Amy Marston"],
    genres: ["Romance", "Comedy", "Holiday"],
    tropes: ["Holiday Romance", "Second Chance"],
    country: "UK",
    rating: 5.9,
    awardWinner: false,
    synopsis: "An American baker inherits a struggling Scottish inn and reluctantly teams up with a skeptical local innkeeper to save it before Christmas.",
    awards: "Nominated — Rose d'Or Award, 2024",
    trivia: "Filmed on location in the Scottish Highlands during the region's real winter season.",
    poster: "linear-gradient(160deg,#1e3a3a,#e5c14a)"
  },
  {
    id: "midnight-in-provence",
    title: "Midnight in Provence",
    year: 2025,
    decade: "2020s",
    runtime: 104,
    director: "Colette Fournier",
    writer: "Colette Fournier, Simon Reyes",
    cast: ["Adria Arjona", "Nicholas Hoult", "Camille Rowe"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Holiday Romance"],
    country: "France",
    rating: 6.8,
    awardWinner: false,
    synopsis: "A burned-out chef inherits a failing vineyard in the south of France and clashes — then falls — for the local winemaker determined to buy her out.",
    awards: "Nominated — César Award, 2025",
    trivia: "The film's vineyard sequences were shot on a working estate in the Luberon region.",
    poster: "linear-gradient(160deg,#3a1e2a,#e5c14a)"
  },
  {
    id: "the-understudy",
    title: "The Understudy",
    year: 2025,
    decade: "2020s",
    runtime: 101,
    director: "Priya Chandrasekaran",
    writer: "Priya Chandrasekaran",
    cast: ["Auli'i Cravalho", "Froy Gutierrez", "Marisa Tomei"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Workplace Romance"],
    country: "USA",
    rating: 6.7,
    awardWinner: false,
    synopsis: "A Broadway understudy finally gets her shot at the lead role opposite the lead actor she can't stand — until opening night forces them together in every sense.",
    awards: "Nominated — Independent Spirit Award, 2025",
    trivia: "Real Broadway theaters were used for several key rehearsal and backstage sequences.",
    poster: "linear-gradient(160deg,#5b2a3e,#e5c14a)"
  },
  {
    id: "one-more-summer",
    title: "One More Summer",
    year: 2025,
    decade: "2020s",
    runtime: 99,
    director: "Marcus Halloway",
    writer: "Marcus Halloway, JadeEnnis",
    cast: ["Maitreyi Ramakrishnan", "Charles Melton", "Bel Powley"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Small Town"],
    country: "USA",
    rating: 6.5,
    awardWinner: false,
    synopsis: "Two former camp counselors who fell for each other one teenage summer reunite a decade later to run the same camp — and finish what they never started.",
    awards: "Nominated — Gotham Award, 2025",
    trivia: "Several of the film's cast attended real summer-camp training to prepare for their roles.",
    poster: "linear-gradient(160deg,#1e2a3a,#d1495b)"
  },
  {
    id: "the-wedding-planner-2026",
    title: "Save the Date",
    year: 2026,
    decade: "2020s",
    runtime: 105,
    director: "Naledi Okafor",
    writer: "Naledi Okafor, Ben Prescott",
    cast: ["Ayo Edebiri", "Anthony Ramos", "Molly Shannon"],
    genres: ["Romance", "Comedy"],
    tropes: ["Wedding", "Enemies to Lovers"],
    country: "USA",
    rating: 6.9,
    awardWinner: false,
    synopsis: "A meticulous wedding planner and a laid-back caterer are forced to share the same venue calendar for an entire summer of dueling weddings.",
    awards: "Nominated — Critics' Choice Award, 2026",
    trivia: "The production built a fully functional working venue set to shoot multiple weddings back to back.",
    poster: "linear-gradient(160deg,#3a2a1e,#e5c14a)"
  },
  {
    id: "return-ticket",
    title: "Return Ticket",
    year: 2026,
    decade: "2020s",
    runtime: 107,
    director: "Elias Vance",
    writer: "Elias Vance",
    cast: ["Sydney Sweeney", "Diego Calva", "Judith Light"],
    genres: ["Romance", "Comedy"],
    tropes: ["Second Chance", "Road Trip"],
    country: "USA",
    rating: 6.6,
    awardWinner: false,
    synopsis: "A delayed flight strands two exes at the same gate for eighteen hours, forcing a conversation neither ever got to finish.",
    awards: "Nominated — Independent Spirit Award, 2026",
    trivia: "The entire film unfolds in real time inside a single airport terminal set.",
    poster: "linear-gradient(160deg,#1e3a3a,#3d6ea5)"
  },
  {
    id: "cafe-society-of-love",
    title: "The Corner Table",
    year: 2026,
    decade: "2020s",
    runtime: 96,
    director: "Ines Moreau",
    writer: "Ines Moreau, Théo Lacombe",
    cast: ["Zendaya", "Callum Turner", "Fanny Ardant"],
    genres: ["Romance", "Comedy"],
    tropes: ["Enemies to Lovers", "Workplace Romance"],
    country: "France",
    rating: 7.0,
    awardWinner: false,
    synopsis: "Two rival food critics assigned to review the same restaurant week after week develop a secret rivalry that slowly curdles into something else entirely.",
    awards: "Nominated — César Award, 2026",
    trivia: "Every restaurant featured in the film is a real, still-operating establishment in Paris.",
    poster: "linear-gradient(160deg,#5b3a1e,#e5c14a)"
  }
];

const QUOTES = [
  { quote: "I'm just a girl, standing in front of a boy, asking him to love her.", movie: "Notting Hill", year: 1999 },
  { quote: "You've got mail.", movie: "You've Got Mail", year: 1998 },
  { quote: "It's a chance I'd rather take with you than have a sure thing without you.", movie: "Sleepless in Seattle", year: 1993 },
  { quote: "To me, you are perfect.", movie: "Love Actually", year: 2003 },
  { quote: "Whatever happens tomorrow, we had today.", movie: "The Notebook", year: 2004 },
  { quote: "I love you. I loved you the whole time.", movie: "(500) Days of Summer", year: 2009 },
  { quote: "The heart wants what it wants. Or maybe it doesn't care what it wants.", movie: "Crazy, Stupid, Love.", year: 2011 },
  { quote: "It's the small, boring things that make a life.", movie: "About Time", year: 2013 }
];

const COLLECTIONS = [
  { id: "wedding", title: "Best Wedding Rom-Coms", filter: m => m.tropes.includes("Wedding"), blurb: "Vows, chaos, and love found mid-ceremony." },
  { id: "christmas", title: "Best Christmas Rom-Coms", filter: m => m.tropes.includes("Holiday Romance"), blurb: "Mistletoe, snow, and second chances." },
  { id: "british", title: "Best British Rom-Coms", filter: m => m.country === "UK", blurb: "Wit, rain, and understated devotion." },
  { id: "teen", title: "Best Teen Rom-Coms", filter: m => m.genres.includes("Teen"), blurb: "First loves and hallway glances." },
  { id: "highest-rated", title: "Highest Rated", filter: m => m.rating >= 7.3, blurb: "The archive's most acclaimed entries." },
  { id: "award-winners", title: "Award Winners", filter: m => m.awardWinner, blurb: "Recognized by critics and academies alike." },
  { id: "underrated", title: "Underrated Gems", filter: m => m.rating >= 6.2 && m.rating < 6.8, blurb: "Quietly brilliant, rarely mentioned first." },
  { id: "cult", title: "Cult Classics", filter: m => ["clueless", "10-things", "500-days-of-summer", "palm-springs"].includes(m.id), blurb: "Films that found devotion long after release." }
];
